/**
 * Scheduled Email Reports — Architecture & Configuration
 *
 * This module provides the client-side configuration UI support
 * and the report generation logic for scheduled email reports.
 *
 * For actual email delivery, you need ONE of these backends:
 *
 * Option A: Supabase Edge Functions + Resend
 *   1. Install Resend: npm install resend
 *   2. Create a Supabase Edge Function (cron-triggered)
 *   3. Generate PDF server-side and email it
 *
 * Option B: Vercel Cron + SendGrid
 *   1. Create /api/cron/weekly-report.js in your Vercel project
 *   2. Configure vercel.json with cron schedule
 *   3. Use SendGrid API to send the email
 *
 * Option C: GitHub Actions (free, no server needed)
 *   1. Create .github/workflows/weekly-report.yml
 *   2. Schedule: cron: '0 9 * * 1' (Monday 9 AM)
 *   3. Run a node script that generates and emails reports
 *
 * The client-side code below handles:
 *   - User preferences (frequency, email, enabled/disabled)
 *   - Report data preparation
 *   - Preview of what the email would contain
 */

import storage from "./storage";

const REPORT_CONFIG_KEY = "email_report_config";

export const defaultConfig = {
  enabled: false,
  email: "",
  frequency: "weekly",     // 'daily', 'weekly', 'monthly'
  dayOfWeek: 1,            // 0=Sun, 1=Mon, ... 6=Sat
  timeOfDay: "09:00",
  includePortfolio: true,
  includeInventory: true,
  includeKPIs: true,
  includeInsights: true,
};

export function getReportConfig() {
  return storage.get(REPORT_CONFIG_KEY, defaultConfig);
}

export function saveReportConfig(config) {
  storage.set(REPORT_CONFIG_KEY, { ...defaultConfig, ...config });
}

/**
 * Prepare report data snapshot for email
 */
export function prepareReportData() {
  const portfolio = storage.get("portfolio_holdings", []);
  const customKPIs = storage.get("custom_kpis", []);
  const customProducts = storage.get("custom_products", []);
  const widgets = storage.get("dashboard_widgets", {});

  return {
    generatedAt: new Date().toISOString(),
    portfolio: {
      holdings: portfolio,
      totalCoins: portfolio.length,
    },
    kpis: customKPIs,
    inventory: {
      customProducts: customProducts,
      totalCustom: customProducts.length,
    },
    dashboardConfig: widgets,
  };
}

/**
 * Generate the email HTML preview
 */
export function generateReportHTML(data) {
  const date = new Date(data.generatedAt).toLocaleDateString("en-US", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });

  return `
    <div style="font-family: 'Inter', sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
      <div style="text-align: center; margin-bottom: 24px;">
        <h1 style="color: #2d2a26; margin: 0;">BizInsight</h1>
        <p style="color: #7d7469; font-size: 12px; text-transform: uppercase; letter-spacing: 2px;">Weekly Analytics Report</p>
        <p style="color: #b5a898; font-size: 13px;">${date}</p>
      </div>

      <div style="background: #f9f6f1; border-radius: 12px; padding: 16px; margin-bottom: 16px;">
        <h3 style="color: #2d2a26; margin: 0 0 12px 0; font-size: 14px;">📊 Portfolio Summary</h3>
        <p style="color: #7d7469; font-size: 13px; margin: 4px 0;">Total coins tracked: ${data.portfolio.totalCoins}</p>
      </div>

      <div style="background: #f9f6f1; border-radius: 12px; padding: 16px; margin-bottom: 16px;">
        <h3 style="color: #2d2a26; margin: 0 0 12px 0; font-size: 14px;">📦 Inventory Summary</h3>
        <p style="color: #7d7469; font-size: 13px; margin: 4px 0;">Custom products: ${data.inventory.totalCustom}</p>
      </div>

      ${data.kpis.length > 0 ? `
      <div style="background: #f9f6f1; border-radius: 12px; padding: 16px; margin-bottom: 16px;">
        <h3 style="color: #2d2a26; margin: 0 0 12px 0; font-size: 14px;">📈 Your KPIs</h3>
        ${data.kpis.map((k) => `<p style="color: #7d7469; font-size: 13px; margin: 4px 0;">${k.title}: <strong>${k.value}</strong> ${k.trend || ""}</p>`).join("")}
      </div>` : ""}

      <div style="text-align: center; margin-top: 24px; padding: 16px; border-top: 1px solid #e8e2d9;">
        <p style="color: #b5a898; font-size: 11px;">This report was auto-generated by BizInsight Analytics Dashboard</p>
      </div>
    </div>
  `;
}

export const FREQUENCY_OPTIONS = [
  { value: "daily", label: "Daily", desc: "Every day at your chosen time" },
  { value: "weekly", label: "Weekly", desc: "Once a week on your chosen day" },
  { value: "monthly", label: "Monthly", desc: "First of every month" },
];

export const DAY_OPTIONS = [
  { value: 0, label: "Sunday" },
  { value: 1, label: "Monday" },
  { value: 2, label: "Tuesday" },
  { value: 3, label: "Wednesday" },
  { value: 4, label: "Thursday" },
  { value: 5, label: "Friday" },
  { value: 6, label: "Saturday" },
];
